spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///student_system?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#DruidDataSource里的属性
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn:  false
    poolPreparedStatements: true
#配置监控统计拦截的filters，去掉后监控界面sql无法统计，‘wall’用于防火墙
    #filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#通过sql语句生成表的配置
    schema:
#      - classpath:/sql/user.sql
#      - classpath: student.sql
#      - classpath: class.sal
# jsp和HTHL不能同时使用
  thymeleaf:
    cache: false
    enabled: false
#     prefix: classpath:/templates/
#上传、下载需要此配置，且使thymeleaf模板失效
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

#配置mybatis
mybatis:
   config-location: classpath:/mybatis/mybatis-config.xml
   mapper-locations: classpath:/mybatis/mapper/*.xml
   typeAliasesPackage: com.ssm.student_system.bean




#配置端口号
server:
    port: 8081
   #multipart:
     #max-file-size: 200MB
     #max-request-size: 200MB
